# Generated by Django 3.0.8 on 2021-04-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_review'),
        ('users', '0003_profile_fund'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='product',
            field=models.ManyToManyField(blank=True, to='posts.Post'),
        ),
    ]
