# Generated by Django 3.0.8 on 2021-03-14 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210306_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='level',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='lft',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='rght',
        ),
        migrations.RemoveField(
            model_name='categories',
            name='tree_id',
        ),
        migrations.AlterField(
            model_name='categories',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='posts.Categories'),
        ),
    ]
